server:
  address: localhost
  port: 8080

spring:
  application:
    name: todoapp

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/todoapp
    username: admin
    password: admin

  main:
    allow-bean-definition-overriding: true
  
kafka:
  bootstrapAddress: ${KAFKA_HOST:localhost}:29092

elk:
  logstash:
    host: ${ELK_LOGSTASH_HOST:localhost}:${ELK_LOGSTASH_PORT:5000}