filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

strict.perms: false
xpack.monitoring.collection.enabled: true